
import { Customer } from './types';

export const customerData: Customer[] = [
  { token: "110", name: "BAGADIYA KOMAL BEN", taxType: "RCG TAX", district: "NIKOL-AHEMBDABD", price: "10,500/-", brokerage: "870/-", status: true },
  { token: "120", name: "MANGUKIYA BHAGVATI BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "14500/-", brokerage: "870/-", status: true },
  { token: "130", name: "KAKADIYA DHARMISTHABEN", taxType: "RCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "140", name: "SUDANI KRISHNABEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "150", name: "SUDANI JEMISHABEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "160", name: "RANPARIYA JAYSHREEBEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "170", name: "THUMAR FORAMBEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "180", name: "TALA SONALBEN MANISHBHAI", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "190", name: "RANGANI HETALBEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "200", name: "KANANI BHAKTIBEN", taxType: "MCLBSG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "210", name: "PATHAN AFZALBHAI", taxType: "HNCG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "220", name: "CHAUHAN MANMOHAN SINH BHAI", taxType: "BSHPG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "230", name: "SHAH RAMESH BHAI", taxType: "RCG TAX", district: "MIRA ROAD-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "240", name: "ANSARI ABDUL BHAI", taxType: "HNCG TAX", district: "NEW MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "250", name: "PATHAN JAVEDBHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "260", name: "PATHAN MOHAMAD BHAI", taxType: "HNCG TAX", district: "NEW MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "270", name: "PATHAN YUSUF BHAI", taxType: "HNCG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "280", name: "LAVRI SANGITA BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "290", name: "JADVANI HARSHA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "300", name: "KHAN IEMRAN BHAI", taxType: "HNCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "310", name: "KANANI NILAM BEN", taxType: "HNCG TAX", district: "NIKOL-AHEMBDABD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "320", name: "KORADIYA AMRUTA BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "330", name: "BADRESHIYA KINJAL BEN", taxType: "HNCG TAX", district: "NANA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "340", name: "PREET RAKUL BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "350", name: "PATHAN USMAN BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "360", name: "KHAN SUFIYAN BHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "370", name: "PATHAN DAOUD BHAI", taxType: "HNCG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "380", name: "KHAN FAISAL BHAI", taxType: "HNCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "390", name: "KHAN RASID BHAI", taxType: "BSHPG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "400", name: "PATHAN NAIYEM BHAI", taxType: "BSHPG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "410", name: "PATHAN JAHID BHAI", taxType: "RCG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "420", name: "PATHAN AHMEAD BHAI", taxType: "BSHPG TAX", district: "NEW COLONEY ROAD-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "430", name: "KHAN AMIR BHAI", taxType: "HNCG TAX", district: "NEW COLONEY ROAD-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "440", name: "PATHAN ARSALAM BHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "450", name: "PATHAN FAIZAN BHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "460", name: "MOLVI HAIDER BHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "470", name: "PATHAN HAISAN BHAI", taxType: "HNCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "480", name: "PATHAN HUSAIN BHAI", taxType: "HNCG TAX", district: "NEW MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "490", name: "PATHAN IBRAHIM BHAI", taxType: "HNCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "500", name: "KHAN IRFAN BHAI", taxType: "HNCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "510", name: "ANSARI JAVED BHAI", taxType: "HNCG TAX", district: "MAGDALLAH-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "520", name: "PATHAN IRFAN BHAI", taxType: "HNCG TAX", district: "JUHAPURA-AHEMBDABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "530", name: "KHAN KASIF BHAI", taxType: "BSHPG TAX", district: "JUHAPURA-AHEMBDABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "540", name: "PATHAN MOHSIN BHAI", taxType: "BSHPG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "550", name: "PATHAN NABIL BHAI", taxType: "RCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "560", name: "PATHAN NADIM BHAI", taxType: "BSHPG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "570", name: "PATHAN NAIEM BHAI", taxType: "BSHPG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "580", name: "KHAN RASID BHAI", taxType: "MCLBSG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "590", name: "PATHAN RIDHVAN BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "600", name: "KHAN SAZID BHAI", taxType: "MCLBSG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "610", name: "PATHAN SALIM BHAI", taxType: "BSHPG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "no", name: "KHAN SALMAN BHAI", taxType: "RCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "620", name: "PATHAN SAMIR BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "630", name: "MOLVI SAKIB BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "640", name: "PATHAN SAHBAZ BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "650", name: "PATHAN SOHIL BHAI", taxType: "MCLBSG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "660", name: "PATHAN TAHIR BHAI", taxType: "MCLBSG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "670", name: "PATHAN TALIB BHAI", taxType: "MCLBSG TAX", district: "ANDHERI,WEST-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "680", name: "PATHAN USMAN BHAI", taxType: "HNCG TAX", district: "ANDHERI,WEST-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "690", name: "HAZIM ABDUL BHAI", taxType: "HNCG TAX", district: "ANDHERI,WEST-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "700", name: "CHAUDHARY MINA BEN", taxType: "RCG TAX", district: "SOMA TALAV-VADORARA", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "710", name: "CHAUDHARY HARSHITA BEN", taxType: "RCG TAX", district: "SOMA TALAV-VADORARA", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "720", name: "CHAUDHARY RIDDHI BEN", taxType: "RCG TAX", district: "SOMA TALAV-VADORARA", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "730", name: "DHOLAKIYA DAKSHA BEN", taxType: "BSHPG TAX", district: "MORDER ROAD-BHAVNAGAR", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "740", name: "DHOLA SAVITA BEN", taxType: "BSHPG TAX", district: "PATEL ROAD-BHAVNAGAR", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "750", name: "DHOLAKIYA DEEPIKA BEN", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "760", name: "MOVALIYA RASHMI BEN", taxType: "RCG TAX", district: "NANA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "770", name: "DHOLAKIYA GITANJALI BEN", taxType: "RCG TAX", district: "PATEL ROAD-BHAVNAGAR", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "780", name: "PATEL ROSHNI BEN", taxType: "RCG TAX", district: "WAGHODIA ROAD-VADODARA", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "790", name: "MAVANI HINA BEN", taxType: "RCG TAX", district: "CHAPRABHATA ROAD-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "800", name: "SUTARIYA HIRAL BEN", taxType: "BSHPG TAX", district: "JEPAR-SURENDRANAGR", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "810", name: "PATHAN SANDHIYABA MOHEMAAD BHAI", taxType: "BSHPG TAX", district: "GEBANSA PIR ROAD-SURENDRANAGR", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "820", name: "SAVALIYA SARITA BEN KISHOR BHAI", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "830", name: "DHOLAKIYA SAVITRI BEN", taxType: "RCG TAX", district: "ADAJAN-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "840", name: "SABHAYA JOSHNA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "850", name: "MANGUKIYA SHETAL BEN", taxType: "RCG TAX", district: "ADAJAN-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "860", name: "KACHIYA SHIPLA BEN", taxType: "BSHPG TAX", district: "CHAPRABHATA ROAD-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "870", name: "SABHAYA SHIVANGI BEN", taxType: "RCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "880", name: "VERMA KAVITA BEN", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "890", name: "SHARMA SONALI BEN", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "900", name: "SHELADIYA SUSHMITA BEN", taxType: "BSHPG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "910", name: "SHELADIYA BHAKTI BEN", taxType: "BSHPG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "920", name: "MADHVANI SHAILAJA BEN", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "930", name: "TALA MADHURI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "940", name: "KORADIYA TRUSHNA BEN", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "950", name: "GABANI NILAM BEN", taxType: "RCG TAX", district: "ADAJAN-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "960", name: "GABANI CHETNA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "970", name: "BHATIA TAMANNAH BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "980", name: "KANANI TRUPTI BEN", taxType: "HNCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "990", name: "PARMAR SNEHAL BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1100", name: "KOLADIYA VARSHA BEN", taxType: "RCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1120", name: "VASOYA BHAGYESHREE BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1130", name: "KHER RINKAL BEN JAVEBHAI", taxType: "HNCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1140", name: "GABANI SHURUSTHI BEN", taxType: "MCLBSG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1150", name: "MERULIYA MANSHVI BEN", taxType: "MCLBSG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1160", name: "SUTARIYA PINAL BEN", taxType: "BSHPG TAX", district: "AMROLI-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1170", name: "MERULIYA BANSHI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1180", name: "KANANI JYOTI BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1190", name: "KANANI PRIYANKA BEN", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1200", name: "FATEHI NORA", taxType: "HNCG TAX", district: "ANDHERI,WEST-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1210", name: "PATHAN ZANKHANABA ABDULJI BHAI", taxType: "HNCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1220", name: "PATHAN PADMANIBA RAHIMDULLAH BHAI", taxType: "BSHPG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1230", name: "PATHAN KINARIBA JAVED BHAI", taxType: "RCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1240", name: "PATHAN SANDHIYABA TAHIR BHAI", taxType: "RCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1250", name: "JADEJA DEVANGI BA", taxType: "RCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1260", name: "JADEJA VANDANA BA", taxType: "RCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1270", name: "JADEJA NEHA BA", taxType: "MCLBSG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1280", name: "JADEJA KOMAL BA", taxType: "RCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1290", name: "VAGHELA RUPALIB BA", taxType: "MCLBSG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1300", name: "JADEJA VAIBHAVI BA", taxType: "MCLBSG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1310", name: "JADEJA PRIYA BA", taxType: "RCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1320", name: "JADEJA DIVYA BA", taxType: "RCG TAX", district: "OLD MAZDID-DELHI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1330", name: "JADEJA PRIYANKA BA", taxType: "RCG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1340", name: "JADEJA ARADHNA BA", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1350", name: "JADEJA DIPALI BA", taxType: "RCG TAX", district: "ADAJAN-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1360", name: "JADEJA BHUMI BA", taxType: "MCLBSG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1370", name: "RAJPOPAT NAIRA BEN", taxType: "BSHPG TAX", district: "GOTRI-VADODARA", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1380", name: "BELADIYA PRIYAL BEN", taxType: "RCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1390", name: "LAVRI SANJANA BEN", taxType: "HNCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1400", name: "JADVANI HIMJA BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1410", name: "MIYANI GOPI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1420", name: "MORADIYA DHRUMI BEN", taxType: "BSHPG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1430", name: "MAANEK DISHA BEN", taxType: "BSHPG TAX", district: "SINDHU BHAVAN ROAD-AHEMBDABAD", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1440", name: "MALIK SAKSHI BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1450", name: "MANJREKAR SAIE BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1460", name: "PATIL MADHVI BEN", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1470", name: "PATIL SANDHYA BEN", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1480", name: "PATIL VILASH BEN", taxType: "RCG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1490", name: "KEVADIYA PRIYANKA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1500", name: "KAPADIYA TINA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1510", name: "TENDULKAR SARA BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1520", name: "AMBANI RADHIKA BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: true },
  { token: "1530", name: "KAUR AVNEET BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1540", name: "MAVANI MEERA BEN", taxType: "RCG TAX", district: "NANA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1550", name: "PANDAY ANANYA BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1560", name: "DONGA DIVYA BEN", taxType: "MCLBSG TAX", district: "FELANGA-HEYDRABAD", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1570", name: "GUNIYAL HIMANSHI BEN", taxType: "MCLBSG TAX", district: "GHATKOPAR-MUMBAI", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1580", name: "VERMA DHANSHREE BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1590", name: "ZUBAIN JANNAT BEN", taxType: "HNCG TAX", district: "GOREGOUE,W-MUMBAI", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1600", name: "GABANI KRINI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1610", name: "RAMPOLIYA KRUPA BEN", taxType: "MCLBSG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1620", name: "VIRANI KHUSHI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1630", name: "VIRANI JALPA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1640", name: "VIRANI KALPANA BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1650", name: "KANANI HAPPY BEN", taxType: "HNCG TAX", district: "NANA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1660", name: "VEKARIYA DHRUVI BEN", taxType: "BSHPG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1670", name: "KORAT HIMANSHI BEN", taxType: "BSHPG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1680", name: "KORAT GEETA BEN", taxType: "RCG TAX", district: "MOTA VARACHA-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1690", name: "MERULIYA DHVANI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1700", name: "DHOLA BHAGVATI BEN", taxType: "RCG TAX", district: "KATARGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
  { token: "1710", name: "VIRANI KUNJIBEN", taxType: "RCG TAX", district: "SIMADAGAM-SURAT", price: "8,500/-", brokerage: "870/-", status: false },
];
